stopping_distance: 0.07
stop_forward_distance: 0.18
max_projection_distance: 0.2
max_skip_turn_go_turn_back_distance: 0.05
new_order_cooldown: 1

prev_pose_memory: 20
prev_pose_save_rate: 2
prev_pose_avoid_distance: 0.2
