set(_CATKIN_CURRENT_PACKAGE "vision")
set(vision_MAINTAINER "ras <ras@todo.todo>")
set(vision_DEPRECATED "")
set(vision_VERSION "0.0.0")
set(vision_BUILD_DEPENDS )
set(vision_RUN_DEPENDS )
set(vision_BUILDTOOL_DEPENDS "catkin")