rate: 100
timeout: 0.5
output_measured_angular: true

motors:
    max_angular_speed: !degrees 180
    max_linear_speed: 1

    gains:
        P: 10
        I: 0
        D: 0.1
        I_memory: 0
    transform:
        constant: 0.088
        exponent: 2.439
        min: 75        # 33 when lifted up, 77 on the floor
        max: 255

