set(_CATKIN_CURRENT_PACKAGE "object_recognizer")
set(object_recognizer_MAINTAINER "ras <ras@todo.todo>")
set(object_recognizer_DEPRECATED "")
set(object_recognizer_VERSION "0.0.0")
set(object_recognizer_BUILD_DEPENDS )
set(object_recognizer_RUN_DEPENDS )
set(object_recognizer_BUILDTOOL_DEPENDS "catkin")